version: "3.9"

services:
  web:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./app:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  php-fpm:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/var/www/html
      - ./app/index.php:/var/www/html/index.php
      - ./app/composer.json:/var/www/html/composer.json
  mysqldb:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "8989:3306"
    volumes:
      - "./data/db/mysql:/var/lib/mysql"

  mysqltestdb:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_TEST_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_TEST_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_TEST_USER}
      - MYSQL_PASSWORD=${MYSQL_TEST_PASSWORD}
    ports:
      - "8991:3306"
    volumes:
      - "./data/db/devmysql:/var/lib/mysql"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: mysqldb
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  phpmyadmintest:
    image: phpmyadmin
    restart: always
    ports:
      - "8092:80"
    environment:
      PMA_HOST: mysqltestdb
      MYSQL_ROOT_PASSWORD: ${MYSQL_TEST_ROOT_PASSWORD}